### ISSUE TITLE
全部搭建完成，但没有菜单

### ISSUE THREAD

**Issue by 3377** [AhFeil/extract_forward_tgbot#1]
项目可以正常运行，保存。但是tg没有菜单该如何处理呢？

**Comment by AhFeil** [comment]
通过 BotFather  设置指令菜单，具体查看 “向 Bot 添加指令” 一节：[Telegram-Bot 的注册和使用 Python 编写 机器人 - 技焉洲 (yanh.tech)](https://yanh.tech/2023/08/register-telegram-bot-and-build-a-bot-using-python/)
