### ISSUE TITLE
可否弄一个统一的记事本地址作为目录?

### ISSUE THREAD

**Issue by Zding89** [AhFeil/extract_forward_tgbot#2]
每次增删推送后可以都通知修改到这个目录地址？
因为tg迷的封号规则，号没了不太好找回，有个目录以后就方便看了

**Comment by AhFeil** [comment]
被封号的话，我觉得可以在第一次使用时，提供一串密钥，其他 tg 账号可以通过密钥取回这个账号转存的消息，这样应该能应对这种情况，你觉得怎么样

**Comment by Zding89** [comment]
> 被封号的话，我觉得可以在第一次使用时，提供一串密钥，其他 tg 账号可以通过密钥取回这个账号转存的消息，这样应该能应对这种情况，你觉得怎么样

这样还得记住密钥，还不如第一次使用让自己输入一个字符串，然后生成这个字符串的目录。访问目录既可以。

**Comment by AhFeil** [comment]
那么流程是这样的：
1. 发送命令 /set persistent <path_str> 
2. 之后再次转发消息的时候，会触发执行 push 操作，将已保存的都放在这个路径中，
3. 每次转发都会覆盖一次，因此这个路径下的始终是最新的。
4. 不会影响机器人的其他行为

OK，周末加上，不错的建议

**Comment by AhFeil** [comment]
设置同步路径： /set persistent path_str 这样格式。取消同步： /set persistent delete。
